### ISSUE TITLE
update instructions to start

### ISSUE THREAD

**Issue by flockonus** [Kay-Zee/BE_music_Kan_Zhang#2]
when I run `node app.js` it doesn't work, can fix why?

```
~/eclipse_workspace/BE_music_Kan_Zhang $ node app.js 

module.js:333
    throw err;
          ^
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/flockonus/eclipse_workspace/BE_music_Kan_Zhang/node_modules/express/node_modules/connect/lib/proto.js:14:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
```

Also got the same error trying to run via the IDE you pointed.

When working in a collaborative project, you have to mind people with different configurations and clear instructions

**Comment by Kay-Zee** [comment]
Have not yet nailed down the exact problem, but I suspect it had something to do with the node_modules on the repo not working properly.

I will update the README.md to include running npm install, but will leave this open until I get a better grasp of why it didn't run

**Comment by flockonus** [comment]
`node_modules` is commonly ignored (.gitignore) and removed from the repo

**Comment by Kay-Zee** [comment]
As I have already removed 'node_modules' from the repo, and added it to .gitignore, I'm hoping that this will fix the problem.

From the error, it looks like it has something to do with the express module in 'node_modules', and possibly due to running on different operating systems, so hopefully requiring everyone to run 'npm install' will fix the problem

**Comment by flockonus** [comment]
Thanks and good job here!

I think the only thing I had to change was to run the results:
`./node_modules/mocha/bin/mocha script.js` because I didn't had Mocha installed globally.
